"""Add perform update field in Product model

Revision ID: 14460e8a5a3d
Revises: a61418d3fed3
Create Date: 2025-01-22 09:57:17.636606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14460e8a5a3d'
down_revision: Union[str, None] = 'a61418d3fed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('perform_update', sa.Boolean(), nullable=False, comment='Обновлять ли товар при запуске, или по времени.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'perform_update')
    # ### end Alembic commands ###
