"""First migration

Revision ID: a61418d3fed3
Revises: 
Create Date: 2025-01-21 15:52:05.597591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61418d3fed3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('name', sa.String(length=250), nullable=False, comment='Уникальное название товара, обязательное строковое поле; допустимая длина строки — от 1 до 250 символов включительно;'),
    sa.Column('article', sa.BigInteger(), nullable=False, comment='Артикул товара в магазине, целочисленное уникальное значение.'),
    sa.Column('price', sa.Float(), nullable=False, comment='Цена товара, положительное число с плавающей запятой.'),
    sa.Column('rating', sa.Float(), nullable=False, comment='Рейтинг товара, число с плавающей запятой от 0 до 5 включительно.'),
    sa.Column('total', sa.BigInteger(), nullable=False, comment='Количесво товара на всех складах.'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Номер в базе данных'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Номер в базе данных'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
